name: Running tests
on: [push, pull_request]
env:
  MODULE_NAME: handlebars_theme_handler
  DRUPAL_REPO: https://git.drupalcode.org/project/drupal.git
  DRUPAL_VERSION: 8.8.x
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Donwload Drupal
        run: git clone --branch ${{env.DRUPAL_VERSION}} ${{env.DRUPAL_REPO}} drupal --depth 1
      - uses: actions/checkout@v2
        with:
          path: drupal/modules
      - name: Run composer
        run: |
          cd drupal
          sed -i "s|\"repositories\": [|\"repositories\": [ {\"type\": \"path\", \"url\": \"core\"},|" composer.json
          composer update
